### ISSUE TITLE
Come up with a name

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/kandy#15]
The working title "ggdsl" doesn't quite fit the idea of our library. First, now the library deviates significantly from the ideas of Grammar of Graphics (i.e. the "gg" part). Secondly, this is not only DSL, but also IR, add-ons for libraries and some other things.

**Comment by devcrocod** [comment]
We have chosen the name "Kandy". This name carries several meanings:
* It references the great artist Kandinsky, whose paintings intersect with the representation of graphs.
* It is associated with candy, because our library is sweet like candy!
* It is also an abbreviation based on the name of the main maintainer — K. Andrey.

For a complete renaming, the following steps are necessary:

- [ ] Merge the renaming branch
- [ ] Rename the repository on github
- [ ] Publish the library with the new name
- [ ] Rename the descriptors for the Kotlin kernel
